### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by PrajaktaSathe** [PrajaktaSathe/Python#33]
- [ ] Add a "contributors" section to the bottom (which will update itself every time someone new contributes)
- [ ] Check and update the list of projects/programs (if that can be updated automatically every time somebody contributes, it would be great!)

If anyone is willing to do this, please let me know!

**Comment by dunchin7** [comment]
Hi, Can you assign this to me?

**Comment by PrajaktaSathe** [comment]
@dunchin7 how much have you implemented?

**Comment by Ayush-Singh-Code** [comment]
You can refer [this](https://github.com/marketplace/actions/auto-add-contributors)
