### ISSUE TITLE
Instance Segmentation with PyTorch

### ISSUE THREAD

**Issue by Mohit-robo** [PrajaktaSathe/Python#82]
I have a collection of 

> Python codes with PyTorch and Keras/Tensorflow for Instance Segmentation, Object Detection with YOLOv4, and Classification.

I also have codes to create 

> CNN, RNN, LSTM, ANN from scratch with Pytorch. 

I also have a project for ``` Object Tracking task with Deep Sort. ```
So can I make PR's for all these projects.

**Comment by PrajaktaSathe** [comment]
Sure!
Go ahead!
